### ISSUE TITLE
Can't connect to external Redis instance

### ISSUE THREAD

**Issue by bberming** [newrelic/nri-redis#100]
I have the issue reported on NewRelic forum but not sure if here is the more appropriate place to connect:
https://discuss.newrelic.com/t/external-redis-connection-reset/127110

I’m trying to configure the NR Redis agent to monitor a remote Redis instance.

The agent is failing with:

> time=“2021-01-14T14:45:46Z” level=error msg=“Integration command failed” error=“exit status 2” instance=redis-test integration=com.newrelic.redis prefix=integration/com.newrelic.redis stderr="[FATAL] can’t continue: read tcp 123.123.123.123:53658->234.234.234.234:123: read: connection reset by peer\npanic: read tcp 123.123.123.123:53658->234.234.234.234:123: read: connection reset by peer\n\ngoroutine 1 [running]:\ngithub.com/newrelic/nri-redis/vendor/github.com/newrelic/infra-integrations-sdk/log.Fatal 1(0x741cc0, 0xc420068870)\n\t/go/src/github.com/newrelic/nri-redis/vendor/github.com/newrelic/infra-integrations-sdk/log/log.go:107 +0xd5\nmain.fatalIfErr(0x741cc0, 0xc420068870)\n\t/go/src/github.com/newrelic/nri-redis/src/redis.go:175 +0x44\nmain.main()\n\t/go/src/github.com/newrelic/nri-redis/src/redis.go:68 +0x15c\n" working-dir=/var/db/newrelic-infra/newrelic-integrations
    time=“2021-01-14T14:45:46Z” level=info msg=“Integration health check finished with some errors” instance=redis-test integration=com.newrelic.redis prefix=integration/com.newrelic.redis working-dir=/var/db/newrelic-infra/newrelic-integrations

I don’t see how to specify the username, this could be the issue as I can get a connection from the same machine through a cli tool but by passing in the username and password.

Here is my config with some data replaced:

    integration_name: com.newrelic.redis

    instances:

        name: redis-test
        command: metrics
        arguments:
        hostname: redis-host.example.com
        port: 1234
        password:
        config_inventory: false
        #keys: ‘{“0”:["<KEY_1>"],“1”:["<KEY_2>"]}’

        remote_monitoring: true

        use_unix_socket: true
        labels:
        environment: test

**Comment by bberming** [comment]
Feature request opened to support username/password
